In [2]:
# !pip install joblib

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [3]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [12]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        

In [15]:
obj = Perceptron(eta=0.01, epochs=10)

In [16]:
obj.eta

0.01

In [17]:
obj.epochs

10

In [18]:
obj.weights

array([ 1.70203736e-04,  4.03171015e-07, -2.92024654e-05])

In [19]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
y = np.ones((4, 1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [22]:
obj.fit(X, y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
